name: seed
favicon: null
layout_spectrum: 0.8041953323408961
typography_spectrum: 0.995581848314032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.36530790850520134
  lightness: 0.3206216371618211
  saturation: 0.7486434390302747
  rhythmicContrast: 0.024073914857581258
purpose: []
